In [23]:
"""
    Broadcasting in Python using Numpy [and its importance in Deep Learning]
    Author: Sadip Giri (sadipgiri@bennington.edu)
    Date: 10th June, 2018
"""

'\n    Broadcasting in Python using Numpy [and its importance in Deep Learning]\n    Author: Sadip Giri (sadipgiri@bennington.edu)\n    Date: 10th June, 2018\n'

In [24]:
import numpy as np
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [25]:
# now adding it to certain number
updated_v = v + 100
print(updated_v)

[101 102 103 104]


In [26]:
# Theoretically, it doesn't make sense since we are adding 1*4 dim. vector to constant
# However, Python does it for us using Broadcasting techniques
# Generally:
# (m,n) + or - or * or / (1,m) or (n, 1)--->(we get) (m, n) 

In [27]:
# Other examples:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)
print("---------- + 100")
updated_mat = mat + 100
print(updated_mat)
print("---------- + [1000, 1000, 1000]")
print(mat + np.array([1000, 1000, 1000]))

[[1 2 3]
 [4 5 6]]
---------- + 100
[[101 102 103]
 [104 105 106]]
---------- + [1000, 1000, 1000]
[[1001 1002 1003]
 [1004 1005 1006]]


In [28]:
matrx = np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0, 52.0, 8.0], [1.8, 135.0, 99.0, 0.9]])
print(matrx)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [29]:
columnwise_sum = matrx.sum(axis=0) # 0 for vertical sum and 1 for horizontal sum
print(columnwise_sum)
print("Now calculating percentage of each components")

# now to take the average and compute percentage
percent_matrx = 100*matrx/columnwise_sum # here we are using Broadcasting techniques of Python [numpy]
print(percent_matrx)


[ 59.  239.  155.4  76.9]
Now calculating percentage of each components
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [30]:
# Note: Broadcasting is very useful techniques in Deep Learning Era with respect to Vectorization